# -*- mode: utf-8 -*-
# vi: ft=yaml.ansible

# ============================================================================ #
# File   : site.yaml                                                           #
# Purpose: Configure systems to use ansible or awx                             #
#                                                                              #
# Author : Harald van der Laan                                                 #
# Date   : 2020-01-17                                                          #
# Version: v1.0.0                                                              #
# ============================================================================ #
# Changelog:                                                                   #
# - v1.0.0: Initial version                              (Harald van der Laan) #
# ============================================================================ #
# Copyright © 2020 Harald van der Laan                                         #
#                                                                              #
# Permission is hereby granted, free of charge, to any person obtaining        #
# a copy of this software and associated documentation files (the "Software"), #
# to deal in the Software without restriction, including without limitation    #
# the rights to use, copy, modify, merge, publish, distribute, sublicense,     #
# and/or sell copies of the Software, and to permit persons to whom the        #
# Software is furnished to do so, subject to the following conditions:         #
#                                                                              #
# The above copyright notice and this permission notice shall be included      #
# in all copies or substantial portions of the Software.                       #
#                                                                              #
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,              #
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES              #
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    #
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,  #
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,                #
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE   #
# OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                #
# ============================================================================ #

---
- hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: facts -> ensure local facts directory is present
      file:
        path: /etc/ansible/facts.d
        state: directory
      register: factsdir

    - name: facts -> ensure local facts file is present
      blockinfile:
        path: /etc/ansible/facts.d/managed.fact
        blovk: |
          [defaults]
          ansible = true
      when: factsdir.changed
